# Generated by Django 6.0.1 on 2026-02-22 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('record_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('contact_call', models.CharField(max_length=255)),
                ('freq', models.FloatField()),
                ('mode', models.CharField(max_length=255)),
                ('sig_rep_sent', models.IntegerField(blank=True, null=True)),
                ('sig_rep_recv', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('grid', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_sent', models.IntegerField(blank=True, null=True)),
                ('serial_recv', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_date', models.DateField()),
                ('contact_time', models.TimeField()),
                ('utc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sid', models.CharField(primary_key=True, serialize=False)),
                ('sess', models.TextField()),
                ('expire', models.DateTimeField()),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('gridloc', models.CharField(blank=True, max_length=255, null=True)),
                ('privilege', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('itu', models.IntegerField(blank=True, null=True)),
                ('utc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
